services:
  - type: worker
    name: character
    env: docker
    dockerfilePath: ./Dockerfile
    plan: pro
    region: singapore
    buildCommand: pip3 install -U -r requirements.txt
    envVars:
      - key: api_id
        value: "29758428"
      - key: api_hash
        value: "51f9369e03f78674ca21aee8dfd1c842"
      - key: TOKEN
        value: "8345134806:AAGc_ygSXBH2rZz7omtpjytraXj_Yyrbr-s"
      - key: mongo_url
        value: "mongodb+srv://wanglin:wanglin@wanglin.ppt93bd.mongodb.net/?retryWrites=true&w=majority"
      - key: GROUP_ID
        value: "-1002356385851"
      - key: sudo_users
        value: "5821905026", "1318826936"
      - key: UPDATE_CHAT
        value: "sasukevipmusicbotsupport"
      - key: SUPPORT_CHAT
        value: "sasukemusicsupportchat"
      - key: PHOTO_URL
        value: "https://files.catbox.moe/sygsr7.jpg", "https://files.catbox.moe/8mpep6.jpg"
      - key: BOT_USERNAME
        value: "charactercollections_bot"
      - key: CHARA_CHANNEL_ID
        value: "-1002459775779"
