services:
  - type: worker
    name: character
    env: docker
    dockerfilePath: ./Dockerfile
    plan: pro
    region: singapore
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    envVars:
      - key: API_ID
        value: "23596049"
      - key: API_HASH
        value: "62c2019123d852fc8cc2092ca879f31c"
      - key: BOT_TOKEN
        value: "7892011487:AAFoX7bEAS3MBO6zzm5NjMyXPecNX2OCdHc"
      - key: MONGO_DB_URI
        value: "mongodb+srv://wanglin:wanglin@wanglin.ppt93bd.mongodb.net/?retryWrites=true&w=majority"
